Repository capactio/website, pull requests merged in 2021-06, with the labels that each got.

#17 Unify and simplify our `capact login` approach
  docs/cli/getting-started.mdx
  docs/example/mattermost-installation.md
  docs/example/rocketchat-installation.md
  docs/installation/aws-eks.md
  docs/operation/diagnostics.md
Labels: area/ci, area/documentation, enhancement

#25 Fix edit link for documentation and hide GitHub stars
  docusaurus.config.js
  src/pages/index.tsx
Labels: area/community, bug

#24 Add info about possible finalizer issues
  docs/operation/common-problems.md
Labels: area/documentation, area/engine

#23 Sync Capact CLI docs with capactio/capact repo
  docs/cli/commands/capact_action_delete.md
  docs/cli/commands/capact_upgrade.md
Labels: area/cli, area/documentation

#27 Update colors for announcement bar and upgrade dependencies
  docusaurus.config.js
  package-lock.json
  package.json
  src/css/custom.css
Labels: area/community, enhancement

#28 Add badges
  .github/workflows/branch-build.yaml
  README.md
Labels: area/documentation, enhancement, security, size/XS
