Repository capactio/website, pull requests merged in 2021-09, with the labels that each got.

#53 Update documentation after changing way of providing additional TypeInstances
  docs/content-development/guide.md
  docs/content-development/terraform-manifests.md
  docs/feature/policies/action-policy.md
  docs/feature/policies/global-policy.md
  docs/feature/policies/overview.md
  docs/operation/diagnostics.md
Labels: enhancement, area/documentation, area/engine

#57 Add Cookie Policy, disclaimer and cookie banner
  docusaurus.config.js
  package-lock.json
  package.json
  src/components/CookiesBanner.module.css
  src/components/CookiesBanner.tsx
  src/pages/cookie-policy.md
  src/pages/disclaimer.md
  src/plugin/gtm.js
  src/theme/Footer.js
Labels: enhancement, area/community, area/documentation

#59 Enable blog and publish the very first blog post
  blog/2021-09-07-introducing-capact.md
  blog/assets/are-you-ready.gif
  blog/assets/capact-example1.svg
  blog/assets/capact-example2.svg
  blog/assets/capact-example3.svg
  blog/assets/capact-example4.svg
  blog/assets/capact-example5.svg
  blog/assets/future-is-now.jpg
  blog/assets/here-we-go-again-again.gif
  blog/authors.yml
  docs/faq.md
  docusaurus.config.js
  package-lock.json
  package.json
  src/css/custom.css
  versioned_docs/version-0.4/faq.md
Labels: enhancement, area/community, area/documentation

#60 Remove @trojan295 from CODEOWNERS
  CODEOWNERS
Labels: enhancement, area/community

#62 Improve grammar and style for the first blog post
  blog/2021-09-07-introducing-capact.md
  blog/assets/capact-example3.svg
Labels: enhancement, area/community

#55 Support multiple parameters
  docs/content-development/guide.md
  docs/example/mattermost-installation.md
  docs/example/rocketchat-installation.md
Labels: documentation, area/documentation

#67 Update initial blog post with 0.5.0 release info
  blog/2021-09-07-introducing-capact.md
  docusaurus.config.js
Labels: enhancement, area/community, area/documentation

#68 Delete duplicated word in the blog post
  blog/2021-09-07-introducing-capact.md
Labels: bug, area/community, area/documentation

#69 Split community-related files from versioned docs
  blog/2021-09-07-introducing-capact.md
  community/code-of-conduct.md
  community/contributing.md
  community/development/_category_.json
  community/development/assets/ci-default-branch-build.svg
  community/development/assets/ci-integration-tests.svg
  community/development/assets/ci-pr-build.svg
  community/development/assets/ci-recreate-cluster.svg
  community/development/assets/github-clone.png
  community/development/assets/github-fork.png
  community/development/ci.md
  community/development/cluster-monitoring.md
  community/development/development-guide.md
  community/development/development-guidelines.md
  community/development/git-workflow.md
  community/governance.md
  community/release.md
  community/slack.md
  docs/architecture/engine-graphql-api.md
  docs/architecture/hub-graphql-api.md
  docs/content-development/guide.md
  docs/content-development/terraform-manifests.md
  docs/faq.md
  docusaurus.config.js
  redirects.js
  sidebars.community.js
  sidebars.docs.js
  versioned_docs/version-0.5/architecture/engine-graphql-api.md
  versioned_docs/version-0.5/architecture/hub-graphql-api.md
  versioned_docs/version-0.5/content-development/guide.md
  versioned_docs/version-0.5/content-development/terraform-manifests.md
  versioned_docs/version-0.5/development/_category_.json
  versioned_docs/version-0.5/development/assets/ci-default-branch-build.svg
  versioned_docs/version-0.5/development/assets/ci-integration-tests.svg
  versioned_docs/version-0.5/development/assets/ci-pr-build.svg
  versioned_docs/version-0.5/development/assets/ci-recreate-cluster.svg
  versioned_docs/version-0.5/development/assets/github-clone.png
  versioned_docs/version-0.5/development/assets/github-fork.png
  versioned_docs/version-0.5/development/ci.md
  versioned_docs/version-0.5/development/cluster-monitoring.md
  versioned_docs/version-0.5/development/development-guide.md
  versioned_docs/version-0.5/development/development-guidelines.md
  versioned_docs/version-0.5/development/git-workflow.md
  versioned_docs/version-0.5/development/release.md
  versioned_docs/version-0.5/faq.md
Labels: enhancement, area/community

#71 Describe user profiles and personas
  community/assets/james.jpg
  community/assets/simone.jpg
  community/user-profiles.md
Labels: enhancement, area/community, area/documentation
