Repository capactio/website, pull requests merged in 2021-12, with the labels that each got.

#85 Update CLI docs
  docs/cli/commands/capact_install.md
  docs/cli/commands/capact_upgrade.md
Labels: area/cli, area/documentation

#87 Sync Capact CLI docs, remove out-dated deprecation note, fix Capact NS name
  community/development/assets/ci-recreate-cluster.svg
  community/development/ci.md
  docs/architecture/assets/runner-arch.svg
  docs/cli/commands/capact_manifest_validate.md
  docs/example/assets/install-gcp.svg
  docs/example/assets/install-in-cluster.svg
Labels: enhancement, area/documentation

#89 Update GoReleaser version
  community/development/development-guide.md
Labels: area/ci, area/documentation

#90 Update Code Owners and project roles
  CODEOWNERS
  community/code-of-conduct.md
  community/governance.md
Labels: area/community

#88 Add 'Meet Capact maintainers (..)' blog post
  blog/2021-12-13-maintainers-interview.md
  blog/authors.yml
Labels: area/community
