Repository capactio/website, pull requests merged in 2021-08, with the labels that each got.

#46 Update development guide, sync CLI docs
  docs/cli/commands/capact_install.md
  docs/development/development-guide.md
Labels: area/community, area/documentation, enhancement

#47 Update links to the latest capact binaries
  docs/cli/getting-started.mdx
  versioned_docs/version-0.4/cli/getting-started.mdx
Labels: area/documentation, bug

#50 Update documentation after required TypeInstance syntax change in Policy
  docs/content-development/terraform-manifests.md
  docs/example/mattermost-installation.md
  docs/feature/policies/global-policy.md
  docs/feature/policies/overview.md
Labels: enhancement, area/documentation

#51 Update syntax for Policy
  docs/feature/policies/action-policy.md
  docs/feature/policies/overview.md
Labels: enhancement, breaking, area/documentation, area/engine

#52 Sync Capact CLI docs with capactio/capact repo
  docs/cli/commands/capact_hub.md
  docs/cli/commands/capact_hub_implementation.md
  docs/cli/commands/capact_hub_implementation_get.md
  docs/cli/commands/capact_hub_interface.md
  docs/cli/commands/capact_hub_interface_browse.md
  docs/cli/commands/capact_hub_interface_get.md
  docs/cli/commands/capact_hub_interfaces.md
Labels: area/ci, area/documentation
