Repository capactio/website, pull requests merged in 2021-07, with the labels that each got.

#30 Fix responsiveness on smaller devices
  package-lock.json
  package.json
  src/components/homepage/GetStarted.module.css
  src/components/homepage/Hero.module.css
  src/components/homepage/WhatIs.module.css
  src/components/layout/FullWidthSection.module.css
  src/css/custom.css
Labels: area/community, bug

#31 Add animated CLI commands preview on homepage
  package-lock.json
  package.json
  src/components/homepage/GetStarted.tsx
  src/components/homepage/GetStartedTerminal.overrides.css
  src/components/homepage/GetStartedTerminal.tsx
Labels: area/community, enhancement

#32 Describe local installation with CLI
  docs/cli/commands/capact.md
  docs/cli/commands/capact_action.md
  docs/cli/commands/capact_action_create.md
  docs/cli/commands/capact_action_delete.md
  docs/cli/commands/capact_action_get.md
  docs/cli/commands/capact_action_run.md
  docs/cli/commands/capact_action_watch.md
  docs/cli/commands/capact_completion.md
  docs/cli/commands/capact_config.md
  docs/cli/commands/capact_config_get-contexts.md
  docs/cli/commands/capact_config_set-context.md
  docs/cli/commands/capact_environment.md
  docs/cli/commands/capact_environment_create.md
  docs/cli/commands/capact_environment_create_kind.md
  docs/cli/commands/capact_environment_delete.md
  docs/cli/commands/capact_environment_delete_kind.md
  docs/cli/commands/capact_hub.md
  docs/cli/commands/capact_hub_implementations.md
  docs/cli/commands/capact_hub_implementations_get.md
  docs/cli/commands/capact_hub_interfaces.md
  docs/cli/commands/capact_hub_interfaces_browse.md
  docs/cli/commands/capact_hub_interfaces_get.md
  docs/cli/commands/capact_install.md
  docs/cli/commands/capact_login.md
  docs/cli/commands/capact_logout.md
  docs/cli/commands/capact_policy.md
  docs/cli/commands/capact_policy_apply.md
  docs/cli/commands/capact_policy_edit.md
  docs/cli/commands/capact_policy_get.md
  docs/cli/commands/capact_typeinstance.md
  docs/cli/commands/capact_typeinstance_apply.md
  docs/cli/commands/capact_typeinstance_create.md
  docs/cli/commands/capact_typeinstance_delete.md
  docs/cli/commands/capact_typeinstance_edit.md
  docs/cli/commands/capact_typeinstance_get.md
  docs/cli/commands/capact_upgrade.md
  docs/cli/commands/capact_validate.md
  docs/cli/commands/capact_version.md
  docs/cli/getting-started.mdx
  docs/example/mattermost-installation.md
  docs/installation/local.md
  docusaurus.config.js
Labels: area/community, area/documentation

#33 Disable search temporarily
  docusaurus.config.js
Labels: area/community, bug

#36 Update release documentation
  docs/development/release.md
Labels: area/ci, area/community, area/documentation

#37 Make homepage terminal static
  package-lock.json
  package.json
  src/components/homepage/GetStartedTerminal.module.css
  src/components/homepage/GetStartedTerminal.overrides.css
  src/components/homepage/GetStartedTerminal.tsx
  src/css/custom.css
  src/css/termynal.css
Labels: area/community, enhancement

#42 Configure search and hero buttons
  docusaurus.config.js
  src/components/homepage/Hero.module.css
  src/components/homepage/Hero.tsx
  src/css/custom.css
Labels: area/community, enhancement

#43 Remove not supported manifests signature
  docs/content-development/guide.md
Labels: area/documentation, area/hub-manifests

#44 Replace not supported ocfRefs in guide.md
  docs/content-development/guide.md
Labels: area/documentation, area/hub-manifests, area/ocf
