Repository capactio/website, pull requests merged in 2022-01, with the labels that each got.

#91 Update Algolia DocSearch API Key and all dependencies
  .github/workflows/branch-build.yaml
  .github/workflows/pr-build.yaml
  README.md
  docusaurus.config.js
  package-lock.json
  package.json
Labels: enhancement, area/community

#92 Fix Rocket.Chat naming
  docs/example/assets/capact-diagram.svg
  docs/example/rocketchat-installation.md
  docs/feature/policies/action-policy.md
  docs/getting-started.mdx
Labels: bug, area/documentation

#97 Replace `workflow_dispatch` URL with a valid one
  community/development/ci.md
Labels: bug, area/documentation

#94 Prepare documentation for Dashboard
  docs/architecture/_category_.json
  docs/architecture/assets/components.svg
  docs/architecture/e2e-architecture.md
  docs/cli/_category_.json
  docs/cli/getting-started.mdx
  docs/content-development/_category_.json
  docs/dashboard-ui/_category_.json
  docs/dashboard-ui/action-management.md
  docs/dashboard-ui/assets/action-create-params.png
  docs/dashboard-ui/assets/action-create-summary.png
  docs/dashboard-ui/assets/action-create-tis.png
  docs/dashboard-ui/assets/action-details-argo-workflow.png
  docs/dashboard-ui/assets/action-details-buttons.png
  docs/dashboard-ui/assets/action-details-navigation.png
  docs/dashboard-ui/assets/action-details.png
  docs/dashboard-ui/assets/action-list.png
  docs/dashboard-ui/assets/hub-interfacegroups.png
  docs/dashboard-ui/assets/hub-interfaces.png
  docs/dashboard-ui/assets/login.png
  docs/dashboard-ui/overview.md
  docs/operation/_category_.json
  hack/make-release.sh
  redirects.js
  versioned_docs/version-0.5/getting-started.mdx
Labels: enhancement, area/documentation, area/dashboard

#96 Update docs connected with populator
  docs/example/public-hub-content.mdx
  docs/installation/air-gap.mdx
  docs/installation/gcp-gke.md
  docs/operation/diagnostics.md
Labels: enhancement, area/cli, area/documentation

#98 Synchronize CLI docs after moving `manifestgen` out of alpha
  docs/cli/commands/capact_alpha.md
  docs/cli/commands/capact_alpha_manifest-gen.md
  docs/cli/commands/capact_manifest.md
  docs/cli/commands/capact_manifest_generate.md
  docs/cli/commands/capact_manifest_generate_attribute.md
  docs/cli/commands/capact_manifest_generate_implementation.md
  docs/cli/commands/capact_manifest_generate_implementation_empty.md
  docs/cli/commands/capact_manifest_generate_implementation_helm.md
  docs/cli/commands/capact_manifest_generate_implementation_terraform.md
  docs/cli/commands/capact_manifest_generate_interface.md
  docs/cli/commands/capact_manifest_generate_interfacegroup.md
  docs/cli/commands/capact_manifest_generate_type.md
Labels: enhancement, area/documentation

#102 Add desc about TypeInstance
  docs/terminology.md
Labels: area/community, area/documentation, area/hub

#103 Bump docusaurus to beta.15
  package-lock.json
  package.json
Labels: enhancement

#105 Update announcement banner for 0.6.0 release
  docusaurus.config.js
Labels: enhancement, area/community

#104 Update release documentation
  community/release.md
Labels: enhancement, area/community

#106 Update docs about additionalRefs
  docs/architecture/e2e-architecture.md
  docs/feature/assets/type-additional-refs.svg
  docs/feature/type-features.md
Labels: enhancement, area/documentation, area/hub, area/hub-manifests
