Repository capactio/website, pull requests merged in 2022-04, with the labels that each got.

#118 Add info about delete revision
  docs/feature/storage-backends/aws-secrets-manager.md
  docs/feature/storage-backends/helm.mdx
  docs/feature/storage-backends/introduction.md
Labels: enhancement, area/documentation

#119 Describe Storage Backend ProtoBuf API changes and TypeInstance Value Fetcher
  docs/content-development/guide.md
  docs/example/mattermost-installation.md
  docs/feature/storage-backends/introduction.md
Labels: enhancement, area/documentation

#120 Update Docusaurus to 2.0.0-beta18
  package-lock.json
  package.json
  src/css/custom.css
Labels: enhancement, area/community

#123 Fix deadlinks
  docs/cli/commands/capact_typeinstance_get.md
  docs/example/public-hub-content.mdx
Labels: bug
