Repository capactio/website, pull requests merged in 2022-03, with the labels that each got.

#112 Fix proto location
  community/development/development-guide.md
Labels: area/documentation

#111 Add policy description about common TypeInstance injection
  docs/feature/policies/action-policy.md
  docs/feature/policies/global-policy.md
  docs/feature/policies/overview.md
Labels: area/documentation, area/engine

#113 Describe AWS Secrets Storage backend
  docs/feature/storage-backends/_category_.json
  docs/feature/storage-backends/aws-secrets-manager.md
  docs/feature/storage-backends/introduction.md
Labels: enhancement, area/documentation, area/hub

#116 Add Helm storage document
  docs/feature/storage-backends/helm.mdx
  docs/feature/storage-backends/introduction.md
Labels: enhancement, area/documentation, area/hub

#114 Update Content development guide
  docs/content-development/guide.md
Labels: enhancement, area/documentation, area/hub-manifests
